Windows build fixes (#446)
* Changed aws-sdk-cpp version from 1.7.36 to 1.7.141

* Fix for error C2259: anonymous-namespace::BufferedLogSystem cannot instantiate abstract class for windows builds

* Modified Flush() function

* Dockerfile refactor to improve build times/success

* Getting the context correct

* CodeBuild running 10.0.143 hosts; revert to older version.  Make image tags unique

* CodeBuild uses an older Docker Windows image- pin to that.

* Docker windows testing hints

* Version bump of dep: aws-sdk-cpp

* Reorder vcpkg steps

* Don't add empty strings to library path

* Fix git command

* Pull in change from PR #386

* Fixed calling EVP_EncryptUpdate and EVP_DecryptUpdate when AAD is NULL

* Removed test size 0 and added test size 5 to fix failure case

* Fix typo: aad

* Pulling in changes from PR#446